classdef AddTwoIntsRequest < robotics.ros.Message
    %AddTwoIntsRequest MATLAB implementation of deep_rl_pckg/AddTwoIntsRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'deep_rl_pckg/AddTwoIntsRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'c72875410e03faa254dbe6932fdd4675' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        StdMsgsInt64Class = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Int64') % Dispatch to MATLAB class for message type std_msgs/Int64
    end
    
    properties (Dependent)
        A
        B
    end
    
    properties (Access = protected)
        Cache = struct('A', [], 'B', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'A', 'B'} % List of non-constant message properties
        ROSPropertyList = {'a', 'b'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = AddTwoIntsRequest(msg)
            %AddTwoIntsRequest Construct the message object AddTwoIntsRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function a = get.A(obj)
            %get.A Get the value for property A
            if isempty(obj.Cache.A)
                obj.Cache.A = feval(obj.StdMsgsInt64Class, obj.JavaMessage.getA);
            end
            a = obj.Cache.A;
        end
        
        function set.A(obj, a)
            %set.A Set the value for property A
            validateattributes(a, {obj.StdMsgsInt64Class}, {'nonempty', 'scalar'}, 'AddTwoIntsRequest', 'A');
            
            obj.JavaMessage.setA(a.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.A)
                obj.Cache.A.setJavaObject(a.getJavaObject);
            end
        end
        
        function b = get.B(obj)
            %get.B Get the value for property B
            if isempty(obj.Cache.B)
                obj.Cache.B = feval(obj.StdMsgsInt64Class, obj.JavaMessage.getB);
            end
            b = obj.Cache.B;
        end
        
        function set.B(obj, b)
            %set.B Set the value for property B
            validateattributes(b, {obj.StdMsgsInt64Class}, {'nonempty', 'scalar'}, 'AddTwoIntsRequest', 'B');
            
            obj.JavaMessage.setB(b.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.B)
                obj.Cache.B.setJavaObject(b.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.A = [];
            obj.Cache.B = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.A = copy(obj.A);
            cpObj.B = copy(obj.B);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.A = feval([obj.StdMsgsInt64Class '.loadobj'], strObj.A);
            obj.B = feval([obj.StdMsgsInt64Class '.loadobj'], strObj.B);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.A = saveobj(obj.A);
            strObj.B = saveobj(obj.B);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.deep_rl_pckg.AddTwoIntsRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.deep_rl_pckg.AddTwoIntsRequest;
            obj.reload(strObj);
        end
    end
end
